### ISSUE TITLE
reprints

### ISSUE THREAD

**Issue by ShichibukaiJinbe** [tetianakh/wishlist-optimizer#1]
doesnt work when cards have multiple print runs

**Comment by tetianakh** [comment]
Cards with multiple print runs have multiple product IDs on mkm, so fetching article data takes a long time. Every request about pricing job status generated a new redis connection. Within approx. 20s redis connection pool becomes exhausted (we have a limit of 20 connections). The solution is to use a singleton queue object to connect to redis instance.
